# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar-multidb}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Staubo"]
  s.date = %q{2010-08-30}
  s.description = %q{Capistrano extension that adds syntax checks for Ruby, ERB and JavaScript files.}
  s.email = %q{alex@bengler.no}
  s.extra_rdoc_files = [
    "LICENSE",
     "LICENSE.closure",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "LICENSE.closure",
     "README.markdown",
     "VERSION",
     "lib/capistrano/ext/syntax_checking.rb",
     "lib/capistrano/ext/syntax_checking/erb.rb",
     "lib/capistrano/ext/syntax_checking/haml.rb",
     "lib/capistrano/ext/syntax_checking/javascript.rb",
     "lib/capistrano/ext/syntax_checking/ruby.rb",
     "lib/capistrano/recipes/syntax_checking.rb",
     "lib/closure/compiler.jar"
  ]
  s.homepage = %q{http://github.com/alexstaubo/capistrano-syntax-checking}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Capistrano extension that adds syntax checks for Ruby, ERB and JavaScript files.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.0"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.0"])
  end
end

