---
name: CI PR Builds
'on':
  push:
    branches:
    - master
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: CI Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
        - '3.4'
        activerecord:
        - '7.1'
        - '7.2'
        - '8.0'
        exclude:
        - ruby: '3.0'
          activerecord: '7.2'
        - ruby: '3.0'
          activerecord: '8.0'
        - ruby: '3.1'
          activerecord: '8.0'
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/activerecord-${{ matrix.activerecord }}.gemfile"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - name: Run bundle update
      run: bundle update
    - name: Run tests
      run: bundle exec rspec
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Coveralls Parallel
      if: "${{ !env.ACT }}"
      uses: coverallsapp/github-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        flag-name: run-${{ matrix.ruby }}-${{ matrix.activerecord }}
        parallel: true
  finish:
    name: All CI Tests Passed
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        if: "${{ !env.ACT }}"
        uses: coverallsapp/github-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          parallel-finished: true
